$SUMMARY: Demonstrates try catch$

try {
	print(getarr(args, 0), "\n");
} catch {
	print("Not enough command line arguments specified!\n");
}
finally {
	$ this code always executes when the try block exits, even if there's been an exception. you can then free resources, close files or connections, etc. $
	println("That's all folks!");
}

exit(0);
